services:
  llamacpp-server:
    image: ghcr.io/ggerganov/llama.cpp:server
    volumes:
      - $PWD/models:/models
    environment:
      # alternatively, you can use "LLAMA_ARG_MODEL_URL" to download the model
      LLAMA_ARG_MODEL: /models/Qwen/Qwen_1.5_8Q.gguf
      LLAMA_ARG_CTX_SIZE: 4096
      LLAMA_ARG_N_PARALLEL: 4
      LLAMA_ARG_ENDPOINT_METRICS: 1
      LLAMA_ARG_PORT: 8000
      LLAMA_ARG_N_PREDICT: 512
    expose:
      - 8000
  nginx:
    depends_on: 
      - llamacpp-server
    build: 
      context: .
      dockerfile: Dockerfile-nginx
    ports: 
      - 80:80
