FROM python:3.10-bullseye as base
LABEL maintainer="Espy Mur.. {}@{}.format(espoir.mur, gmail)"

# Setup env
ENV LANG=C.UTF-8
ENV LC_ALL=C.UTF-8
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONFAULTHANDLER=1
ENV SETUPTOOLS_SCM_PRETEND_VERSION=0.1.0
ARG PIP_SECTION


FROM base AS python-deps

# Install uv and compilation dependencies
RUN pip install uv

RUN apt-get update && apt-get install -y \
    build-essential \
    libxslt1-dev \
    && rm -rf /var/lib/apt/lists/*

# Install python dependencies in /.venv
COPY pyproject.toml .
COPY uv.lock .
COPY src/_version.py src/_version.py
RUN uv venv --python 3.10 /.venv
RUN uv sync --frozen --no-dev --no-editable --group ${PIP_SECTION}

FROM python:3.10-slim AS runtime

RUN apt-get update && apt-get install -y \
    libxslt1.1 \
    && rm -rf /var/lib/apt/lists/*

# Copy virtual env from python-deps stage
COPY --from=python-deps /.venv /.venv
ENV PATH="/.venv/bin:$PATH"
ENV WORKDIR="/home/appuser"

RUN useradd --create-home es.py
RUN mkdir /home/code
ENV WORKING_DIR=/home/code
ENV PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python
COPY src ${WORKING_DIR}/src
COPY src/shared ${WORKING_DIR}/src/shared
WORKDIR ${WORKING_DIR}
RUN chown -R es.py:es.py ${WORKING_DIR}
RUN chmod -R 755 ${WORKING_DIR}
USER es.py
