services:
  news-summarizer:
    image: espymur/summarization-clustering:latest
    tty: true
    volumes:
      - ${PWD}/models/dunzhang/stella_en_400M_v5:/home/summarizer/models/dunzhang/stella_en_400M_v5
    env_file:
      - ../.env_prod
    labels:
      ofelia.enabled: "true"
      ofelia.job-exec.summarizer.schedule:  "0 25 23 * * *"
      ofelia.job-exec.summarizer.command: "python src/summarizer/main.py -e prod -d 0"

  ofelia:
    image: mcuadros/ofelia:latest
    restart: "unless-stopped"
    depends_on:
      - news-summarizer
    command: daemon --docker -f label=com.docker.compose.project=${COMPOSE_PROJECT_NAME}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
