FROM python:3.10-bullseye as base
LABEL maintainer="Espy Mur.. {}@{}.format(espoir.mur, gmail)"

# Setup env
ENV LANG=C.UTF-8
ENV LC_ALL=C.UTF-8
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONFAULTHANDLER=1
ENV SETUPTOOLS_SCM_PRETEND_VERSION=0.1.0
ARG PIP_SECTION


FROM base AS python-deps

# Install uv and compilation dependencies
RUN pip install uv

RUN apt-get update && apt-get install -y \
    build-essential \
    libxslt1-dev \
    && rm -rf /var/lib/apt/lists/*

ENV WORKDIR=/app
WORKDIR ${WORKDIR}

COPY ./src/ ${WORKDIR}
COPY ./src/_version.py ${WORKDIR}/src/
COPY pyproject.toml ${WORKDIR}
COPY uv.lock ${WORKDIR}

RUN uv sync --frozen --no-dev --no-editable --group ${PIP_SECTION}

FROM python:3.10-slim AS runtime

RUN apt-get update && apt-get install -y \
    libxslt1.1 \
    && rm -rf /var/lib/apt/lists/*

# Setup a non-root user
RUN groupadd --system --gid 999 es.py \
 && useradd --system --gid 999 --uid 999 --create-home es.py

COPY --from=python-deps --chown=es.py:es.py /app /app

ENV PATH="/app/.venv/bin:$PATH"
ENV WORKDIR="/app"
ENV PYTHONUSERBASE=$PATH

ENV PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python
COPY src ${WORKDIR}/src
ENV PYTHONPATH="${PATH}:${WORKDIR}"
WORKDIR ${WORKDIR}
RUN chown -R es.py:es.py ${WORKDIR}
RUN chmod -R 755 ${WORKDIR}
USER es.py
