services:
  news-summarizer-clustering:
    image: espymur/summarization-clustering:latest
    tty: true
    volumes:
      - ${PWD}/models/dunzhang/stella_en_400M_v5:/home/code/models/dunzhang/stella_en_400M_v5
    env_file:
      - ../.env_local
    labels:
      ofelia.enabled: "true"
      ofelia.job-exec.clustering.schedule:  "0 00 22 * * *"
      ofelia.job-exec.clustering.command: "python src/summarizer/main.py -e local -st b2 -d 0"

  ofelia:
    image: mcuadros/ofelia:latest
    restart: "unless-stopped"
    depends_on:
      - news-summarizer-clustering
      - news-summarizer-generative-model
    command: daemon --docker -f label=com.docker.compose.project=${COMPOSE_PROJECT_NAME}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    
  news-summarizer-generative-model:
    image: espymur/summarization-generator:latest
    tty: true
    env_file:
      - ../.env_local
    network_mode: host
    labels:
      ofelia.enabled: "true"
      ofelia.job-exec.summarizer.schedule:  "0 30 22 * * *"
      ofelia.job-exec.summarizer.command: "python src/llm/main.py"
