apiVersion: v1
kind: Namespace
metadata:
  name: flyte
  labels:
    name: flyte
---

kind: PersistentVolume
apiVersion: v1
metadata:
  name: minio-pv
  namespace: flyte
spec:
  storageClassName: hostpath
  capacity:
    storage: 25Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /data
  claimRef:
    name: minio-pvc
    namespace: flyte



---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-pvc
  namespace: flyte
spec:
  storageClassName: hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  volumeName: minio-pv


--- 

apiVersion: apps/v1 #  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: Deployment
metadata:
  # This name uniquely identifies the Deployment
  name: minio
  namespace: flyte
  labels:
    app.kubernetes.io/name: minio
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: minio
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        # Label is used as selector in the service.
        app.kubernetes.io/name: minio
    spec:
      containers:
      - name: minio
        # Pulls the default Minio image from Docker Hub
        image: docker.io/bitnami/minio:2024
        imagePullPolicy: IfNotPresent
        env:
        # Minio access key and secret key
          - name: MINIO_ROOT_USER
            value: minio 
          - name: MINIO_ROOT_PASSWORD
            value: miniostorage
          - name: MINIO_DEFAULT_BUCKETS
            value: flyte
          - name: MINIO_DATA_DIR
            value: "/data"
          - name: MINIO_BROWSER_LOGIN_ANIMATION
            value: 'off'
        ports:
        - containerPort: 9000
          name: minio
        - containerPort: 9001
          name: minio-console
        # Mount the volume into the pod
        resources: 
          limits:
            cpu: 200m
            memory: 512Mi
          requests:
            cpu: 10m
            memory: 128Mi
        volumeMounts:
        - name:  minio-storage # must match the volume name, above
          mountPath: "/data"
      volumes:
      - name: minio-storage
        persistentVolumeClaim:
          claimName: minio-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: flyte
  labels: 
    app.kubernetes.io/name: minio
spec:
  type: NodePort
  ports:
  - name: minio
    nodePort: 30084
    port: 9000
    protocol: TCP
    targetPort: minio
  - name: minio-console
    nodePort: 30088
    port: 9001
    protocol: TCP
    targetPort: minio-console
  selector: 
    app.kubernetes.io/name: minio
