name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Build Docker Image for th generator
      run: |
        docker buildx build --platform linux/amd64,linux/arm64 -t ${{ vars.DOCKER_USERNAME }}/summarization-generator:latest -f docker/Dockerfile-base --build-arg PIP_SECTION=generator-packages .
    
    - name: Build Docker Image clustering
      run: |
        docker buildx build --platform linux/amd64,linux/arm64 -t ${{ vars.DOCKER_USERNAME }}/summarization-clustering:latest -f docker/Dockerfile-base --build-arg PIP_SECTION=clustering-packages .
    - name: Push Docker Image
      run: |
        docker push ${{ vars.DOCKER_USERNAME }}/summarization-clustering:latest
        docker push ${{ vars.DOCKER_USERNAME }}/summarization-generator:latest
